framework:
  github: ohler55/agoo
  version: 2.12

environment:
  # FIXME: how to compute this
  AGOO_WORKER_COUNT: $(nproc)

command: /usr/src/app/bin/bundle exec /usr/bin/ruby /usr/src/app/app.rb

files:
  - app.rb
  - Gemfile

bootstrap:
  - bundle config set without "development test"
  - bundle config set path "vendor/bundle"
  - bundle install
  - bundle binstubs bundler
